name: Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

env:
  USER_NAME: shavera
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: build base image
        run: docker build . -t local/project-base -f project-base.Dockerfile

      - name: build and push project builder
        id: cmake_builder
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ci-cmake-builder
          file: builder.Dockerfile

      - name: build and push unit tester
        id: unit_test
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ci-unit-test
          file: unit-test.Dockerfile

      - name: build and push sonar scanner
        id: sonar_scanner
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ci-sonar-scanner
          file: sonar-scanner.Dockerfile