name: Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches: main

env:
  USER_NAME: shavera
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build ci-tooling
        id: ci_tooling
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shavera/ci-tooling
